In [1]:
import numpy as np

In [2]:
np

<module 'numpy' from '/Users/bastienwinant/Desktop/Projects/ml-zoomcamp/.env/lib/python3.9/site-packages/numpy/__init__.py'>

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
size = 10
value = 2.5
np.full(size,value)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
l = [1,2,3,4]
a = np.array(l)
a[3] = 5
a

array([1, 2, 3, 5])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.linspace(0, 10, 16)

array([ 0.        ,  0.66666667,  1.33333333,  2.        ,  2.66666667,
        3.33333333,  4.        ,  4.66666667,  5.33333333,  6.        ,
        6.66666667,  7.33333333,  8.        ,  8.66666667,  9.33333333,
       10.        ])

In [9]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
a = np.array([[1,3,4,5], [7,8,9,10]])
a[1,3]

10

In [11]:
a[1] # get the second row

array([ 7,  8,  9, 10])

In [12]:
a[:,2] # get the second column

array([4, 9])

In [13]:
np.random.seed(2) # for reproducibility
np.random.rand(5, 2) # standard uniform distribution

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [14]:
np.random.randn(5, 2) # standard normal distribution

array([[ 0.55145404,  2.29220801],
       [ 0.04153939, -1.11792545],
       [ 0.53905832, -0.5961597 ],
       [-0.0191305 ,  1.17500122],
       [-0.74787095,  0.00902525]])

In [15]:
np.random.randint(low=2, high=5, size=(5,2))

array([[3, 4],
       [2, 2],
       [4, 2],
       [4, 2],
       [4, 3]])

In [16]:
a = np.arange(5)

In [17]:
a

array([0, 1, 2, 3, 4])

In [18]:
a + 2

array([2, 3, 4, 5, 6])

In [19]:
b = a + np.random.randn(5)

In [20]:
a + b

array([-0.45571477, -0.12452767,  4.54979824,  4.83209975,  9.08006357])

In [21]:
a < b

array([False, False,  True, False,  True])

In [22]:
a[a < b] # select the elements in a that are smaller than the corresponding elemements in b

array([2, 4])

In [23]:
a.sum()

10

In [24]:
a.mean()

2.0

In [25]:
a.max()

4